apiVersion: v1
kind: Service
metadata:
  name: trend-service
spec:
  type: LoadBalancer
  selector:
    app: trend
  ports:
    - protocol: TCP
      port: 80         # Public facing web ingress port
      targetPort: 3000 # Redirects traffic to the application's internal listening port
